heat_template_version: 2015-10-15

description: >
  This template will boot a cluster with one or more nodes (as specified by the
  number_of_nodes parameter, which defaults to "1").

parameters:
  #
  # REQUIRED PARAMETERS
  #
  ssh_key_name:
    type: string
    label: Key name
    description: Name of key-pair to be installed on the compute instance.

  external_network:
    type: string
    label: Public network name or ID
    description: Public network with floating IP addresses.

  #
  # OPTIONAL PARAMETERS
  #
  server_image:
    type: string
    label: Image name or ID
    description: >
        Image to be used for the server. Please use an Ubuntu based image.
    default: cirros

  server_flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used on the compute instance.
    default: m1.small

  number_of_nodes:
    type: string
    description: How many Kolla nodes to spawn.
    default: 1

  # fixed_network
  internal_network_cidr:
    type: string
    label: Network CIDR
    description: The CIDR of the private IP network.
    default: '10.0.0.0/24'

  dns_nameserver:
    type: comma_delimited_list
    label: DNS nameservers
    description: Comma separated list of DNS nameservers for the private net.
    default: '8.8.8.8'

resources:
  ######################################################################
  # Resources
  #

  # Create SecGroups once for all nodes
  security_groups:
    type: lib/security_groups.yaml

  internal_network:
    type: lib/internal_network.yaml
    properties:
      cidr: { get_param: internal_network_cidr }
      dns_nameserver: { get_param: dns_nameserver }
      external_network: { get_param: external_network }

  node:
    type: lib/node.yaml
    properties:
      image: { get_param: server_image }
      flavor: { get_param: server_flavor }
      key_name: { get_param: ssh_key_name }
      internal_network: { get_attr: [internal_network, name] }
      external_network: { get_param: external_network }
      security_groups: { get_resource: security_groups }


outputs:
  instance_name:
    description: Name of the instance
    value: { get_attr: [node, name] }

  kolla_node_internal_ip:
    description: The IP address of internal network
    value: { get_attr: [node, ip] }

  #kolla_node_external_ip:
  #  description: The IP address of the deployed instance
  #  value: { get_attr: [floating_ip, ip] }
